{
  "name": "FileInUseException",
  "comment": "FileInUseException indicates that there was contention\n for a file which is in-use.  This can be caused for various reasons\n including a file lock of some kind.",
  "javadoc": "\u003ccode\u003eFileInUseException\u003c/code\u003e indicates that there was contention\n for a file which is in-use.  This can be caused for various reasons\n including a file lock of some kind.",
  "static": false,
  "implements": [],
  "extends": "java.io.IOException",
  "fields": [],
  "methods": [
    {
      "name": "\u003cinit\u003e",
      "comment": "Create a new FileInUseException with the given message.",
      "javadoc": "Create a new FileInUseException with the given message.\n@param msg the exception message.",
      "static": false,
      "params": [
        {
          "name": "msg",
          "type_long": "java.lang.String",
          "type_short": "String",
          "comment": "the exception message."
        }
      ],
      "return": {
        "type_long": "void",
        "type_short": "void",
        "comment": ""
      },
      "throws": []
    },
    {
      "name": "\u003cinit\u003e",
      "comment": "Create a new FileInUseException with the given message and cause.",
      "javadoc": "Create a new FileInUseException with the given message and cause.\n@param msg the exception message.",
      "static": false,
      "params": [
        {
          "name": "msg",
          "type_long": "java.lang.String",
          "type_short": "String",
          "comment": "the exception message."
        },
        {
          "name": "cause",
          "type_long": "java.lang.Throwable",
          "type_short": "Throwable",
          "comment": ""
        }
      ],
      "return": {
        "type_long": "void",
        "type_short": "void",
        "comment": ""
      },
      "throws": []
    }
  ]
}
